### ISSUE TITLE
eslint and React

### ISSUE THREAD

**Issue by justin808** [adametry/gulp-eslint#51] opened 2015-04-05 01:02 UTC
I'm depending on this to be a peer of eslint:

```
    "eslint-plugin-react": "^2.0.2",
```

Otherwise, I get errors like this:
```
/Users/justin/j/react/react-webpack-rails-tutorial/client/assets/javascripts/Comment.jsx
  3:0  error  'import' and 'export' may appear only with 'sourceType: module'
```

You can reproduce this issue with this repo:

https://github.com/justin808/react-webpack-rails-tutorial

And running `gulp lint`

Compare to running the `bin/lint` script.

Basically, the issue comes down to how should sibling eslint dependencies be handled.

**Comment by adametry** [comment] 2015-04-15 02:58
It appears that react-webpack-rails-tutorial has a direct dependency on the "react" plugin (eslint-plugin-react) within its `.eslintrc` file. Since the project has the direct dependency, it is currently correct to include it as a dependency in the `package.json` file. 

When running `bin/lint`, I find the following included in the output:
```shell
Cannot read config file: [...]/react-webpack-rails-tutorial/client/.eslintrc
Error:  Unexpected token p
```
This suggests that, when `bin/lint` scans for an `eslint` command, it likely finds an old version of eslint that is unable to read the YAML `.eslintrc` and therefore doesn't load the "react" plugin.

Try checking the eslint version by adding the `-v` flag to the find command, like so:
```shell
find . -path ./node_modules -prune -o -name "*.js" -o -name "*.jsx" -exec eslint -v {} \;
```
This will repeat the eslint version number for each file it finds.

If `bin/lint` is updated to use a local install of eslint, the results are the same as gulp-eslint.
```shell
node_modules/eslint/bin/eslint.js .
```

In fact, you can even remove the direct dependency on eslint and just use gulp-eslint as long as you have the eslint-plugin-react dependency included in your `project.json`.

**Comment by adametry** [comment] 2015-04-26 17:11
Since the issue is not with gulp-eslint, I'm closing this. Let me know if you need any further detail.

**Closed by adametry** 2015-04-26 17:11 UTC
