### ISSUE TITLE
eslint shows only first error

### ISSUE THREAD

**Issue by Diokuz** [adametry/gulp-eslint#118] opened 2015-11-13 08:25 UTC
How to configure gulp-eslint in such a way, that it will show all errors at once?

Now I have to make gulp-eslint after each error fix, because it shows only first detected error.

1.1.0.

**Comment by Diokuz** [comment] 2015-11-13 08:26
Wow, I solved the problem) Just removed that line:
```js
.pipe(eslint.failOnError());
```
Maybe it should not be in examples)

**Comment by adametry** [comment] 2015-11-13 15:55
Which example did you find it in? It's not in the ["fix" example](https://github.com/adametry/gulp-eslint/blob/master/example/fix.js), and the first example in [README.md](https://github.com/adametry/gulp-eslint#usage) uses `failAfterError`. The only full example of its use is in the ["fail-immediately" task](https://github.com/adametry/gulp-eslint/blob/b00c579a01b52597756eb7b9d45b1926adc611ef/example/fail.js#L16) in which the example reports and fails as soon as possible. For an example of how to report all errors (at once) before failing, look at the ["fail-at-end" task](https://github.com/adametry/gulp-eslint/blob/b00c579a01b52597756eb7b9d45b1926adc611ef/example/fail.js#L16) in that same example file.

**Comment by adametry** [comment] 2015-11-13 15:57
I'll close this since the issue is resolved; though, I can still clarify any confusion regarding the API.

**Closed by adametry** 2015-11-13 15:57 UTC

**Comment by Diokuz** [comment] 2015-11-16 06:53
Example was in "usage" section for [1.0.0 version](https://github.com/adametry/gulp-eslint/tree/v1.0.0#usage).
Now the problem is solved, thanks.
