### ISSUE TITLE
update ESLINT version

### ISSUE THREAD

**Issue by yairEO** [adametry/gulp-eslint#151] opened 2016-05-02 09:30 UTC
Hi, will you be willing to upgrade the ESLINT version used for your wrapper?

Thanks.

**Comment by adametry** [comment] 2016-05-02 13:09
It already is. Be sure to update your local node_modules to use it.

**Comment by shinnn** [comment] 2016-05-12 10:58
Duplicate of https://github.com/adametry/gulp-eslint/issues/131.

**Closed** 2016-05-12 10:58 UTC
