### ISSUE TITLE
node v0.12 can no longer use this plugin

### ISSUE THREAD

**Issue by stezu** [adametry/gulp-eslint#170] opened 2016-08-13 14:53 UTC
In 7228608ae0ed3f553f81621e5b4450b71a7b4bae, this plugin was modified to use ES2015 features as well as a new eslint plugin which breaks compatibility with node v0.12. This plugin should have an [engines](https://docs.npmjs.com/files/package.json#engines) property in package.json to indicate that this plugin only works on node v4+.

The main ESLint package.json does this [here](https://github.com/eslint/eslint/blob/master/package.json#L118).

Specifically this plugin fails for the following reasons:
* `const` is not supported in strict mode according to [node.green](http://node.green/#const).
* arrow functions are not supported according to [node.green](http://node.green/#arrow-functions).

**Comment by shinnn** [comment] 2016-08-18 03:48
This issue is a duplicate of https://github.com/adametry/gulp-eslint/issues/165, and my argument is https://github.com/adametry/gulp-eslint/issues/165#issuecomment-235950790.

Let's hear the opinion of the maintainer @adametry.

**Comment by shinnn** [comment] 2016-08-22 08:24
No feedback.

**Closed by shinnn** 2016-08-22 08:24 UTC
