### ISSUE TITLE
failOnError() shows no file or line information with the error

### ISSUE THREAD

**Issue by sym3tri** [adametry/gulp-eslint#12] opened 2014-08-06 23:11 UTC
It just outputs the error message and a stack trace:

```sh
/Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/node_modules/map-stream/index.js:103
        throw err
              ^
ESLintError in plugin 'gulp-eslint'
Strings must use singlequote.
    at /Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/index.js:67:13
    at Array.some (native)
    at /Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/index.js:58:12
    at wrappedMapper (/Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/node_modules/map-stream/index.js:96:21)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at queueData (/Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/node_modules/map-stream/index.js:43:21)
    at next (/Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/node_modules/map-stream/index.js:71:7)
    at /Users/ed/dev/go/src/github.com/coreos-inc/roller/cp/node_modules/gulp-eslint/node_modules/map-stream/index.js:85:7
```

**Comment by adametry** [comment] 2015-01-26 04:40
@anddoutoi, can you clone this repo and run `npm run throw-on-error` followed by `echo $?` to print the last exit code?

I see the following:
```bash
[22:05:48] Starting 'throw'...
[22:05:49] 'throw' errored after 865 ms
[22:05:49] ESLintError in plugin 'gulp-eslint'
Message:
    Missing "use strict" statement.
Details:
    fileName: /Users/adamreeves/Documents/Resources/GitHub/gulp-eslint/test/fixtures/use-strict.js
    lineNumber: 1
```

However, if the issue is that the `format` messages aren't displayed (maybe because the processed is killed before stderror is flushed), try using `formatEach`. It prints lint messages immediately, before piping to the next stream.

```javascript
gulp.src( stagedFilePaths )
	.pipe( eslint() )
	.pipe( eslint.formatEach() )
	.pipe( eslint.failOnError() );
```

**Comment by adametry** [comment] 2015-01-26 05:24
In the latest version, I've added an experimental failAfterError method that will wait until the stream ends to fail the stream. This method better works with the `format` method.

**Comment by adametry** [comment] 2015-01-26 15:25
I'm going to close this issue since there is a published solution. I can reopen it if more work is needed.

**Closed by adametry** 2015-01-26 15:25 UTC

**Comment by anddoutoi** [comment] 2015-01-26 17:04
@adametry thank you. Atm I'm not working on our quality tools but I'll be sure to try this out as soon as I get a new QA item into a sprint. It looks very promising =)

**Comment by kristianmandrup** [comment] 2015-07-19 15:46
Hi there, I'm having the same kind of problem. No real error messages, even when using `failAfterError`:

```sh
16:32 $ npm test

> trains-es6@0.0.1 test /Users/kristianmandrup/repos/Thoughtworks/trains-es6
> gulp
```sh
[16:35:19] Using gulpfile ~/repos/Thoughtworks/trains-es6/gulpfile.js
[16:35:19] Starting 'lint-src'...
[16:35:20] Finished 'lint-src' after 687 ms
[16:35:20] Starting 'test'...
npm ERR! Test failed.  See above for more details.
```

There is no "above" with details for why it failed :(

```js
const gulp = require('gulp');
const $ = require('gulp-load-plugins')();
const del = require('del');
const path = require('path');
const mkdirp = require('mkdirp');
const isparta = require('isparta');

const manifest = require('./package.json');
const config = manifest.nodeBoilerplateOptions;
const mainFile = manifest.main;
const destinationFolder = path.dirname(mainFile);

const eslint = require('gulp-eslint');

// Remove the built files
gulp.task('clean', function(cb) {
  del([destinationFolder], cb);
});

// Send a notification when JSHint fails,
// so that you know your changes didn't build
// function jshintNotify(file) {
//   if (!file.jshint) { return; }
//   return file.jshint.success ? false : 'JSHint failed';
// }

// function jscsNotify(file) {
//   if (!file.jscs) { return; }
//   return file.jscs.success ? false : 'JSCS failed';
// }

function createLintTask(taskName, files) {
  gulp.task(taskName, function () {
    return gulp.src(files)
      // eslint() attaches the lint output to the eslint property
      // of the file object so it can be used by other modules.

      .pipe(eslint())

      // eslint.format() outputs the lint results to the console.
      // Alternatively use eslint.formatEach() (see Docs).

      // list of Formatters!!
      // https://github.com/eslint/eslint/tree/master/lib/formatters

      .pipe(eslint.format())

      // To have the process exit with an error code (1) on
      // lint error, return the stream and pipe to failOnError last.
      // .pipe(eslint.failOnError());

      .pipe(eslint.failAfterError());

      //.pipe($.notify(eslintNotify))
      // .pipe($.jscs())
      // .pipe($.notify(jscsNotify))
  });
}

// Lint our source code
createLintTask('lint-src', ['src/**/*.js']);

// Build two versions of the library
gulp.task('build', ['lint-src', 'clean'], function() {

  // Create our output directory
  mkdirp.sync(destinationFolder);
  return gulp.src('src/**/*.js')
    .pipe($.plumber())
    .pipe($.babel({ blacklist: ['useStrict'] }))
    .pipe(gulp.dest(destinationFolder));
});

function test() {
  return gulp.src(['test/setup/node.js', 'test/unit/**/*.js'], {read: false})
    .pipe($.plumber())
    .pipe($.mocha({reporter: 'dot', globals: config.mochaGlobals}));
}

// Make babel preprocess the scripts the user tries to import from here on.
require('babel/register')({
  stage: 0
});

// Lint and run our tests
gulp.task('test', ['lint-src'], test);

// Run the headless unit tests as you make changes.
gulp.task('watch', ['test'], function() {
  gulp.watch(['src/**/*', 'test/**/*', 'package.json', '**/.eshintrc', '.jscsrc'], ['test']);
});

// An alias of test
gulp.task('default', ['test']);
```

It worked fine with jshint, which I switched away from to gain the ES6/7 benefits from ESlint, such as
linting with support for babel  `stage: 0` experimental additions (class properties etc.).

```js
function jshintNotify(file) {
   if (!file.jshint) { return; }
   return file.jshint.success ? false : 'JSHint failed';
 }
```

In the `gulp.task` it then included `.pipe($.notify(jshintNotify))` and .pipe($.notify(jscsNotify)). 

I wonder if I need to do sth. similar for `eslint` ?

**Comment by adametry** [comment] 2015-10-24 15:33
@kristianmandrup , it appears that gulp finishes the lint task with no warnings/errors, and then fails during your "test" task (i.e., `$.mocha(...`). The "npm ERR! Test failed.  See above for more details." is the message that `npm test` displays when the [script "test" process exits with a non-zero exit code](https://github.com/npm/npm/blob/master/lib/test.js#L9). Since there is no other message, I can only assume that the test is calling `process.exit(1)`.

Anyway, if you can demonstrate how gulp-eslint is involved in your issue, please create a new issue so it can be tracked.
